easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Secteur
       - App\Entity\Pigment
       - App\Entity\Additif
       - App\Entity\Nanomateriaux
       - App\Entity\Sujet